version: "3.9"

services:

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"


  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend/certs:/app/certs


  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend